### PR TITLE
Ballot fix and more code cleaning

### LINKED ISSUE #58: Drop token from vote
Only show the result after voting. 
There is no need to show your own vote unless there is a possibility to change your vote. 

Save tokens used to vote in ballot instead of saving the token in vote.

### PR DESCRIPTION
**Pull request by marcschwaiger**
Closes #58 and #64

### CODE REVIEW

File: src/router.ts [hunk 1]
```diff
@@ -51,8 +50,8 @@ authRouter.post("/login", adminLoginLimiter, AuthController.login);
 const apiKeyRouter = Router();
 baseRouter.use("/api-key", apiKeyRouter);
 apiKeyRouter.get("/", isAdmin, APIKeyController.getApiKeys);
-apiKeyRouter.post("/", isAdmin, APIKeyController.add);
-apiKeyRouter.delete("/", isAdmin, APIKeyController.delete);
+apiKeyRouter.post("/", isAdmin, APIKeyController.addApiKey);
+apiKeyRouter.delete("/", isAdmin, APIKeyController.deleteApiKey);
```
Comment (LeoTuet) [inline src/router.ts]: I have to say that I don't like the addition of the "class/file" name in the method names. Because you already have the name in the "class/file" therefore it isn't needed in the method.
@94726 I don't know if you see it the same way.

File: src/repositories/BallotRepository.ts [hunk 2]
```diff
@@ -61,4 +62,38 @@ export default {
...
+    if (!result.acknowledged) throw Error("Token could not be set as used");
+  },
+  async checkIfTokenIsUsed(ballotId: string, token: string): Promise<boolean> {
+    return (
+      (await getCollection("ballot")
+        .find({
+          _id: new ObjectId(ballotId),
+          tokensUsed: { $elemMatch: { $eq: token } },
+        })
+        .count()) > 0
```
Comment (LeoTuet) [inline src/repositories/BallotRepository.ts]: I think you can use [findeOne](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOne/) here.

**Review by LeoTuet — CHANGES_REQUESTED** [review]
Could you please sum up all your changes in an issue for the frontend.
Cause its hard for me to keep track over the changed variable names.

File: src/router.ts (hunk 1 above)
Comment (94726) [reply src/router.ts]: To be completely honest, I am somewhat pissed that half of the changes could be deemed as useless and time wasting.
So yes, I see it the same way, but it also doesn't matter, just a bit unnecessary.

Half of the codebase got reworked twice, because of a whim. Not to say that all of it was useless, but I think this whole "code cleaning" thing is a bit overdone, especially the opinionated changes...

**Review by LeoTuet — APPROVED** [review]

**Review by 94726 — APPROVED** [review]
